### ISSUE TITLE
issueinNEWrepo contract should be deployed

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/newRepo#1]
issueinNEWrepo

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x99d45e321d3996c4c9d35106a32461fe4799ae051ec537462a68ebaea81aafe0](https://ropsten.etherscan.io/tx/0x99d45e321d3996c4c9d35106a32461fe4799ae051ec537462a68ebaea81aafe0)
